[build]
command = "npm run build"
publish = "public/"
targetPort = 8080
functions = "functions"

[functions]
included_files = ["functions/emails/*"]

[develop]
framework = "gatsby"
targetPort = 8080
command = "npm run develop"
